name: Delete named schedules develop

on:
  push:
    branches: [ develop ]
    paths: [ schedules/** ]

env:
  BIGEYE_CREDENTIALS: ${{ secrets.CLI_CREDS_DEV }}
  BIGEYE_CONFIG: ${{ secrets.CLI_CONFIG_DEV }}

jobs:
   delete_named_schedules:

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Changed files
      uses: tj-actions/changed-files@v44
      id: verify-changed-files
      with:
        files: |
          schedules/*.{yaml,yml}

    - name: Delete named schedules
      if: steps.verify-changed-files.outputs.any_deleted == 'true'
      env:
        DELETED_FILES: ${{ steps.verify-changed-files.outputs.deleted_files }}    
      run: |
          python -m pip install --upgrade pip
          python -m pip install bigeye-cli
    
          echo "$BIGEYE_CONFIG" >> config.ini
          echo "$BIGEYE_CREDENTIALS" >> credentials.ini
          for file in ${DELETED_FILES}; do
            deleted_commit=$(git rev-list --max-count=1 --all -- "${file}")
            sname=$(git show "${deleted_commit}"^:"${file}" | yq '.schedule_name')
            echo "Deleting schedule ${sname}"
            bigeye workspace delete-named-schedule --bigeye_conf credentials.ini --config_file config.ini --name "${sname}"
          done
          