name: Delta CICD develop
on:
  pull_request:
    paths: [ deltas/cicd/** ]


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  CURRENT_REPO: ${{ github.repository }}
  BIGEYE_CREDENTIALS: ${{ secrets.CLI_CREDS_DEV }}
  BIGEYE_CONFIG: ${{ secrets.CLI_CONFIG_DEV }}

jobs:
  delta_cicd_example:    
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Changed files
      uses: tj-actions/changed-files@v44
      id: verify-changed-files
      with:
        files: |
          deltas/cicd/*.{yaml,yml} 

    - name: Run Deltas CICD Audit
      if: steps.verify-changed-files.outputs.any_changed == 'true'
      env:
        CHANGED_FILES: ${{ steps.verify-changed-files.outputs.all_changed_files }}    
      run: |
          python -m pip install --upgrade pip
          python -m pip install bigeye-cli
    
          echo "$BIGEYE_CONFIG" >> config.ini
          echo "$BIGEYE_CREDENTIALS" >> credentials.ini
          for file in ${CHANGED_FILES}; do
            bigeye deltas cicd --bigeye_conf credentials.ini --config_file config.ini -dcc "${file}"
          done
      