name: Deploy virtual tables develop

on:
  push:
    branches: [ develop ]
    paths: [ virtual_tables/** ]

env:
  BIGEYE_CREDENTIALS: ${{ secrets.CLI_CREDS_DEV }}
  BIGEYE_CONFIG: ${{ secrets.CLI_CONFIG_DEV }}

jobs:
  deploy_virtual_tables:

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Changed files
      uses: tj-actions/changed-files@v44
      id: verify-changed-files
      with:
        files: |
          virtual_tables/**/*.{yaml,yml}

    - name: Deploy virtual tables
      if: steps.verify-changed-files.outputs.any_changed == 'true'
      env:
        CHANGED_FILES: ${{ steps.verify-changed-files.outputs.all_changed_files }}    
      run: |
          python -m pip install --upgrade pip
          python -m pip install bigeye-cli
    
          echo "$BIGEYE_CONFIG" >> config.ini
          echo "$BIGEYE_CREDENTIALS" >> credentials.ini
          for file in ${CHANGED_FILES}; do
            echo "Virtual table upsert for ${file}"
            vtn=$(cat ${file} | yq '.table_name')
            sn=$(cat ${file} | yq '.source_name')
            sql=$(cat ${file} | yq '.sql')
            bigeye catalog upsert-virtual-table --bigeye_conf credentials.ini --config_file config.ini -vtn "${vtn}" -sn "${sn}" --sql "${sql}"
          done
          