name: Plan Bigconfig develop

on:
  pull_request:
    branches: [ develop ]
    paths: 
      - bigconfig/*_deployments/**/*.yaml
      - bigconfig/*_deployments/**/*.yml
  

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  CURRENT_REPO: ${{ github.repository }}
  BIGEYE_CREDENTIALS: ${{ secrets.CLI_CREDS_DEV }}
  BIGEYE_CONFIG: ${{ secrets.CLI_CONFIG_DEV }}

jobs:
  plan_bigconfig:

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Plan bigconfig        
      run: |
          python -m pip install --upgrade pip
          python -m pip install bigeye-cli
    
          echo "$BIGEYE_CONFIG" >> config.ini
          echo "$BIGEYE_CREDENTIALS" >> credentials.ini          
          bigeye bigconfig plan --bigeye_conf credentials.ini --config_file config.ini --input_path bigconfig --recursive --cicd_report

          